import { config as baseConfig } from "@workspace/eslint-config/base"

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...baseConfig,
  // schema.d.ts is generated by openapi-typescript. Linting it would only ever
  // produce findings nobody is allowed to fix by hand.
  { ignores: ["schema.d.ts"] },
]
