/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness of the API and its database */
    get: operations["HealthController_check"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    HealthDto_Output: {
      /** @enum {string} */
      status: "ok"
      meta: {
        id: number
        version: string
        /** Format: date-time */
        updatedAt: string
      }
    }
    ApiErrorDto: {
      /** @enum {string} */
      code:
        | "common.internal"
        | "common.validationFailed"
        | "common.responseContractViolation"
        | "common.badRequest"
        | "common.unauthenticated"
        | "common.forbidden"
        | "common.notFound"
        | "common.conflict"
        | "common.tooManyRequests"
        | "common.unavailable"
        | "validation.invalidType"
        | "validation.invalidValue"
        | "validation.invalidFormat"
        | "validation.invalidUnion"
        | "validation.invalidKey"
        | "validation.invalidElement"
        | "validation.tooSmall"
        | "validation.tooBig"
        | "validation.notMultipleOf"
        | "validation.unrecognizedKeys"
        | "validation.custom"
        | "health.appMetaMissing"
      message: string
      params?: {
        [key: string]: unknown
      }
      issues?: {
        path: string
        /** @enum {string} */
        code:
          | "common.internal"
          | "common.validationFailed"
          | "common.responseContractViolation"
          | "common.badRequest"
          | "common.unauthenticated"
          | "common.forbidden"
          | "common.notFound"
          | "common.conflict"
          | "common.tooManyRequests"
          | "common.unavailable"
          | "validation.invalidType"
          | "validation.invalidValue"
          | "validation.invalidFormat"
          | "validation.invalidUnion"
          | "validation.invalidKey"
          | "validation.invalidElement"
          | "validation.tooSmall"
          | "validation.tooBig"
          | "validation.notMultipleOf"
          | "validation.unrecognizedKeys"
          | "validation.custom"
          | "health.appMetaMissing"
        message: string
        params?: {
          [key: string]: unknown
        }
      }[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HealthDto_Output"]
        }
      }
      /** @description The request failed validation; `issues` names the fields */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ApiErrorDto"]
        }
      }
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ApiErrorDto"]
        }
      }
      /** @description The database is reachable but has not been migrated */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ApiErrorDto"]
        }
      }
    }
  }
}
